import { Activity, CalendarDays, Check, ChevronDown, ChevronRight, Download, Dumbbell, Gauge, History, Home, LogOut, Plus, Save, ShieldCheck, Sparkles, Target, Trophy, UserRound, X, Zap } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { athleteApi } from '../../features/athlete/api';
import type { AthletePersonalRecord, AthleteProfile, AthleteResultEntry, AthleteWorkout, SaveAthleteResult } from '../../features/athlete/types';

type Tab = 'today' | 'history' | 'records' | 'profile';

export function AthleteDashboard({ profile, initialWorkouts }: { profile: AthleteProfile; initialWorkouts: AthleteWorkout[] }) {
  const [tab, setTab] = useState<Tab>('today');
  const [workouts, setWorkouts] = useState(initialWorkouts);
  const [records, setRecords] = useState<AthletePersonalRecord[]>([]);
  const [boxId, setBoxId] = useState(profile.memberships[0]?.id ?? '');
  const [selected, setSelected] = useState<AthleteWorkout>();
  const [editing, setEditing] = useState<AthleteWorkout>();
  const [message, setMessage] = useState('');
  const [installPrompt, setInstallPrompt] = useState<Event & { prompt?: () => Promise<void> }>();

  useEffect(() => { athleteApi.personalRecords().then(setRecords).catch(() => undefined); }, []);
  useEffect(() => { const listener = (event: Event) => { event.preventDefault(); setInstallPrompt(event as Event & { prompt?: () => Promise<void> }); }; window.addEventListener('beforeinstallprompt', listener); return () => window.removeEventListener('beforeinstallprompt', listener); }, []);

  const visible = useMemo(() => workouts.filter((workout) => !boxId || workout.membership_id === boxId || (!workout.membership_id && profile.memberships.find((item) => item.id === boxId)?.box_name === workout.box_name)), [workouts, boxId, profile.memberships]);
  const featured = useMemo(() => featuredWorkout(visible), [visible]);
  const selectedMembership = profile.memberships.find((item) => item.id === boxId);

  async function refresh() {
    const [nextWorkouts, nextRecords] = await Promise.all([athleteApi.workouts(), athleteApi.personalRecords()]);
    setWorkouts(nextWorkouts); setRecords(nextRecords);
  }
  async function logout() { await athleteApi.logout().catch(() => undefined); window.location.hash = '/athlete/login'; }
  async function confirmRecord(id: string) { await athleteApi.confirmPersonalRecord(id); await refresh(); setMessage('PR confirmado no seu histórico.'); }

  return <div className="min-h-[100dvh] bg-[#f4f6f9] pb-28 text-slate-950">
    <header className="relative overflow-hidden bg-[#071426] px-5 pb-12 pt-[max(1.25rem,env(safe-area-inset-top))] text-white">
      <div className="absolute -right-16 -top-20 h-56 w-56 rounded-full bg-cyan-400/10 blur-2xl" /><div className="absolute -bottom-24 -left-20 h-52 w-52 rounded-full bg-orange-500/15 blur-3xl" />
      <div className="relative mx-auto max-w-xl"><div className="flex items-center justify-between"><Brand /><button onClick={() => setTab('profile')} className="grid h-11 w-11 place-items-center rounded-full border border-white/15 bg-white/10 font-black" aria-label="Abrir perfil">{initials(profile.name)}</button></div>
        <p className="mt-8 text-sm font-semibold text-slate-300">{greeting()}, {firstName(profile.name)}</p><h1 className="mt-1 text-3xl font-black tracking-[-.035em]">{tabTitle(tab)}</h1>
        {profile.memberships.length > 1 ? <label className="relative mt-5 inline-flex items-center"><Dumbbell className="pointer-events-none absolute left-3 h-4 w-4 text-orange-400" /><select aria-label="Selecionar academia" value={boxId} onChange={(event) => setBoxId(event.target.value)} className="appearance-none rounded-full border border-white/10 bg-white/10 py-2 pl-9 pr-9 text-xs font-bold text-white outline-none"><option className="text-slate-950" value="">Todos os boxes</option>{profile.memberships.map((item) => <option className="text-slate-950" key={item.id} value={item.id}>{item.box_name}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 h-4 w-4" /></label> : <div className="mt-5 inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-2 text-xs font-bold"><Dumbbell className="h-4 w-4 text-orange-400" />{selectedMembership?.box_name}</div>}
      </div>
    </header>
    <main className="relative z-10 mx-auto -mt-7 max-w-xl px-4">{message && <button onClick={() => setMessage('')} className="mb-4 flex w-full items-center justify-between rounded-2xl bg-emerald-50 p-4 text-left text-sm font-bold text-emerald-800"><span className="flex items-center gap-2"><Check className="h-4 w-4" />{message}</span><X className="h-4 w-4" /></button>}
      {tab === 'today' && <Today workout={featured} onOpen={setSelected} onRecord={setEditing} />}
      {tab === 'history' && <HistoryView workouts={visible} onOpen={setSelected} />}
      {tab === 'records' && <RecordsView records={records} onConfirm={confirmRecord} />}
      {tab === 'profile' && <ProfileView profile={profile} installPrompt={installPrompt} onInstall={() => void installPrompt?.prompt?.()} onLogout={logout} onVerification={() => athleteApi.requestEmailVerification().then(() => setMessage('Enviamos o link de confirmação para seu e-mail.'))} />}
    </main>
    <nav className="fixed inset-x-0 bottom-0 z-30 border-t border-slate-200/80 bg-white/95 px-3 pb-[max(.65rem,env(safe-area-inset-bottom))] pt-2 shadow-[0_-12px_30px_rgba(15,23,42,.08)] backdrop-blur-xl"><div className="mx-auto grid max-w-md grid-cols-4"><Nav active={tab === 'today'} icon={Home} label="Hoje" onClick={() => setTab('today')} /><Nav active={tab === 'history'} icon={History} label="Histórico" onClick={() => setTab('history')} /><Nav active={tab === 'records'} icon={Trophy} label="PRs" onClick={() => setTab('records')} /><Nav active={tab === 'profile'} icon={UserRound} label="Perfil" onClick={() => setTab('profile')} /></div></nav>
    {selected && <WorkoutDetail workout={selected} onClose={() => setSelected(undefined)} onRecord={() => { setEditing(selected); setSelected(undefined); }} />}
    {editing && <ResultEditor workout={editing} onClose={() => setEditing(undefined)} onSaved={async (possibleRecords) => { setEditing(undefined); await refresh(); setMessage(possibleRecords > 0 ? `${possibleRecords} possível PR encontrado. Confirme na aba PRs.` : 'Resultado salvo no seu histórico.'); }} />}
  </div>;
}

function Today({ workout, onOpen, onRecord }: { workout?: AthleteWorkout; onOpen: (w: AthleteWorkout) => void; onRecord: (w: AthleteWorkout) => void }) {
  if (!workout) return <Empty />;
  return <div className="space-y-4"><button onClick={() => onOpen(workout)} className="w-full overflow-hidden rounded-[28px] bg-white text-left shadow-[0_18px_50px_rgba(15,23,42,.1)]"><div className="border-b border-slate-100 p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-orange-600">{relativeDate(workout.workout_date)}</p><h2 className="mt-1 text-2xl font-black">{workout.title}</h2><p className="mt-1 text-sm text-slate-500">{workout.box_name}</p></div><div className="grid h-12 w-12 place-items-center rounded-2xl bg-orange-50 text-orange-600"><Zap className="h-6 w-6" /></div></div><div className="mt-4 flex flex-wrap gap-2">{workout.classification?.formats?.map((format) => <Pill key={format}>{formatLabel(format)}</Pill>)}</div></div><div className="space-y-2 p-3">{workout.classification?.sections?.slice(0, 3).map((section, index) => <div key={`${section.type}-${index}`} className={`rounded-2xl p-4 ${section.type === 'wod' ? 'bg-[#071426] text-white' : 'bg-slate-50'}`}><p className="text-xs font-extrabold uppercase tracking-wide text-orange-500">{sectionLabel(section.type)}</p><p className="mt-1 font-black">{section.title}</p></div>)}<div className="flex items-center justify-end gap-1 px-2 py-2 text-sm font-bold text-orange-600">Ver treino completo <ChevronRight className="h-4 w-4" /></div></div></button>
    <Insight workout={workout} />
    <button onClick={() => onRecord(workout)} className={`flex w-full items-center justify-center gap-2 rounded-2xl px-5 py-4 text-sm font-extrabold text-white shadow-lg ${workout.result ? 'bg-emerald-600 shadow-emerald-600/20' : 'bg-orange-500 shadow-orange-500/20'}`}><Save className="h-5 w-5" />{workout.result ? 'Editar meu resultado' : 'Registrar meu resultado'}</button>
  </div>;
}

function Insight({ workout }: { workout: AthleteWorkout }) { const p = workout.personalization; const [explanation,setExplanation]=useState('');const[loading,setLoading]=useState(false);async function explain(){setLoading(true);try{const value=await athleteApi.explainWorkout(workout.id);setExplanation(value.body);}finally{setLoading(false)}}return <section className="space-y-3 rounded-[28px] border border-cyan-100 bg-cyan-50 p-5"><div className="flex gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-cyan-500 text-white"><Sparkles className="h-5 w-5" /></div><div><p className="text-xs font-black uppercase tracking-wide text-cyan-700">Estratégia pessoal</p><p className="mt-1 text-sm leading-6 text-slate-700">{p?.summary}</p></div></div><div className="rounded-2xl bg-white/80 p-4"><p className="flex items-center gap-2 text-xs font-black uppercase text-slate-500"><Gauge className="h-4 w-4 text-orange-500" />Pacing</p><p className="mt-2 text-sm leading-6 text-slate-700">{p?.pacing}</p></div>{p?.guidance?.map((item) => <div key={item.movement} className="rounded-2xl bg-white/80 p-4"><p className="font-extrabold">{item.movement}</p><p className="mt-1 text-sm leading-6 text-slate-600">{item.message}</p></div>)}{explanation?<div className="rounded-2xl bg-[#071426] p-4 text-white"><p className="text-xs font-black uppercase tracking-wide text-cyan-300">Explicação contextual</p><p className="mt-2 text-sm leading-6 text-slate-200">{explanation}</p></div>:<button onClick={()=>void explain()} disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-2xl border border-cyan-200 bg-white py-3 text-sm font-extrabold text-cyan-700 disabled:opacity-60"><Sparkles className="h-4 w-4" />{loading?'Preparando explicação...':'Explicar este treino para mim'}</button>}</section>; }

function HistoryView({ workouts, onOpen }: { workouts: AthleteWorkout[]; onOpen: (w: AthleteWorkout) => void }) { return <div className="space-y-4"><div className="px-1"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-orange-600">Sua jornada</p><h2 className="mt-1 text-2xl font-black">Treinos e resultados</h2><h2 className="sr-only">Treinos publicados</h2></div>{workouts.length === 0 ? <Empty /> : workouts.map((workout) => <button key={workout.id} onClick={() => onOpen(workout)} className="flex w-full items-center gap-4 rounded-3xl bg-white p-5 text-left shadow-[0_10px_30px_rgba(15,23,42,.07)]"><div className={`grid h-12 w-12 shrink-0 place-items-center rounded-2xl ${workout.result ? 'bg-emerald-50 text-emerald-600' : 'bg-slate-100 text-slate-700'}`}>{workout.result ? <Check className="h-5 w-5" /> : <CalendarDays className="h-5 w-5" />}</div><div className="min-w-0 flex-1"><p className="text-xs font-bold uppercase tracking-wide text-orange-600">{formatDate(workout.workout_date)}</p><h3 className="mt-1 truncate text-lg font-black">{workout.title}</h3><p className="mt-1 text-sm text-slate-500">{workout.box_name} · {workout.result ? resultSummary(workout.result.entries[0]) : 'Sem resultado'}</p></div><ChevronRight className="h-5 w-5 text-slate-300" /></button>)}</div>; }

function RecordsView({ records, onConfirm }: { records: AthletePersonalRecord[]; onConfirm: (id: string) => Promise<void> }) { return <div className="space-y-4"><div className="px-1"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-orange-600">Evolução pessoal</p><h2 className="mt-1 text-2xl font-black">Meus recordes</h2><p className="mt-2 text-sm text-slate-500">O EngageFit sugere possíveis PRs a partir dos seus resultados. Você decide quais são oficiais.</p></div>{records.length === 0 ? <section className="rounded-[28px] bg-white p-7 text-center"><Trophy className="mx-auto h-10 w-10 text-orange-500" /><h3 className="mt-4 font-black">Seu primeiro PR começa no próximo resultado</h3></section> : records.map((record) => <article key={record.id} className="rounded-[28px] bg-white p-5 shadow-[0_10px_30px_rgba(15,23,42,.07)]"><div className="flex items-start justify-between"><div><p className="text-xs font-black uppercase tracking-wide text-orange-600">{metricLabel(record.metric)}</p><h3 className="mt-1 text-xl font-black">{record.movement_name}</h3></div><Trophy className={`h-7 w-7 ${record.status === 'confirmed' ? 'text-amber-500' : 'text-slate-300'}`} /></div><p className="mt-5 text-3xl font-black">{recordValue(record)}</p><p className="mt-1 text-xs text-slate-500">Alcançado em {formatDate(record.achieved_at.slice(0, 10))}</p>{record.status === 'estimated' ? <button onClick={() => void onConfirm(record.id)} className="mt-4 w-full rounded-2xl bg-orange-500 py-3 text-sm font-extrabold text-white">Confirmar como meu PR</button> : <p className="mt-4 flex items-center gap-2 text-sm font-bold text-emerald-700"><ShieldCheck className="h-4 w-4" />PR confirmado por você</p>}</article>)}</div>; }

function WorkoutDetail({ workout, onClose, onRecord }: { workout: AthleteWorkout; onClose: () => void; onRecord: () => void }) { return <Modal onClose={onClose}><div className="flex items-start justify-between"><div><p className="text-xs font-black uppercase tracking-wide text-orange-600">{formatDate(workout.workout_date)}</p><h2 className="mt-1 text-2xl font-black">{workout.title}</h2><p className="text-sm text-slate-500">{workout.box_name}</p></div><Close onClick={onClose} /></div><div className="mt-5 space-y-3">{workout.classification?.sections?.map((section, index) => <section key={`${section.type}-${index}`} className={`rounded-3xl p-4 ${section.type === 'wod' ? 'bg-[#071426] text-white' : 'bg-slate-50'}`}><p className="text-xs font-black uppercase tracking-wide text-orange-500">{sectionLabel(section.type)}</p><h3 className="mt-2 font-black">{section.title}</h3><p className={`mt-2 whitespace-pre-wrap text-sm leading-7 ${section.type === 'wod' ? 'text-slate-200' : 'text-slate-700'}`}>{section.content}</p></section>) ?? <pre>{workout.raw_text}</pre>}</div><Insight workout={workout} /><button onClick={onRecord} className="mt-5 flex w-full items-center justify-center gap-2 rounded-2xl bg-orange-500 py-4 text-sm font-extrabold text-white"><Save className="h-5 w-5" />{workout.result ? 'Editar resultado' : 'Registrar resultado'}</button></Modal>; }

function ResultEditor({ workout, onClose, onSaved }: { workout: AthleteWorkout; onClose: () => void; onSaved: (possibleRecords: number) => Promise<void> }) {
  const [scale, setScale] = useState<SaveAthleteResult['scale']>(workout.result?.scale ?? 'scaled'); const [rpe, setRpe] = useState(workout.result?.rpe ?? 7); const [notes, setNotes] = useState(workout.result?.notes ?? '');
  const [entries, setEntries] = useState<AthleteResultEntry[]>(workout.result?.entries?.length ? workout.result.entries : [newEntry(workout)]); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  function update(index: number, patch: Partial<AthleteResultEntry>) { setEntries((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item)); }
  async function save() { setSaving(true); setError(''); try { const response = await athleteApi.saveResult(workout.id, { scale, rpe, notes, entries }); await onSaved(response.possible_records.length); } catch (err) { setError(err instanceof Error ? err.message : 'Não foi possível salvar.'); setSaving(false); } }
  return <Modal onClose={onClose}><div className="flex items-start justify-between"><div><p className="text-xs font-black uppercase tracking-wide text-orange-600">Meu resultado</p><h2 className="mt-1 text-2xl font-black">{workout.title}</h2></div><Close onClick={onClose} /></div>
    <div className="mt-5"><p className="text-sm font-bold text-slate-700">Como você fez o treino?</p><div className="mt-2 grid grid-cols-3 gap-2">{(['rx','scaled','adapted'] as const).map((value) => <button key={value} onClick={() => setScale(value)} className={`rounded-2xl border py-3 text-sm font-extrabold ${scale === value ? 'border-orange-500 bg-orange-50 text-orange-700' : 'border-slate-200'}`}>{scaleLabel(value)}</button>)}</div></div>
    <div className="mt-5 space-y-4">{entries.map((entry, index) => <EntryEditor key={index} entry={entry} sections={workout.classification?.sections ?? []} onChange={(patch) => update(index, patch)} onRemove={entries.length > 1 ? () => setEntries((current) => current.filter((_, itemIndex) => itemIndex !== index)) : undefined} />)}</div>
    <button onClick={() => setEntries((current) => [...current, newEntry(workout)])} className="mt-3 flex items-center gap-2 text-sm font-extrabold text-orange-600"><Plus className="h-4 w-4" />Adicionar outro resultado ou movimento</button>
    <label className="mt-5 block text-sm font-bold text-slate-700">Esforço percebido: <strong className="text-orange-600">{rpe}/10</strong><input className="mt-2 w-full accent-orange-500" type="range" min="1" max="10" value={rpe} onChange={(event) => setRpe(Number(event.target.value))} /></label>
    <label className="mt-4 block text-sm font-bold text-slate-700">Observações<textarea value={notes} maxLength={2000} onChange={(event) => setNotes(event.target.value)} placeholder="Como você se sentiu? Fez alguma adaptação?" className="mt-2 min-h-24 w-full rounded-2xl border border-slate-200 bg-slate-50 p-3 font-normal outline-none focus:border-orange-400" /></label>
    {error && <p className="mt-4 rounded-2xl bg-rose-50 p-3 text-sm font-bold text-rose-700">{error}</p>}<button disabled={saving} onClick={() => void save()} className="mt-5 flex w-full items-center justify-center gap-2 rounded-2xl bg-orange-500 py-4 text-sm font-extrabold text-white disabled:opacity-60"><Save className="h-5 w-5" />{saving ? 'Salvando...' : 'Salvar no meu histórico'}</button>
  </Modal>;
}

function EntryEditor({ entry, sections, onChange, onRemove }: { entry: AthleteResultEntry; sections: Array<{ type: string; title: string }>; onChange: (patch: Partial<AthleteResultEntry>) => void; onRemove?: () => void }) { return <section className="rounded-3xl bg-slate-50 p-4"><div className="flex justify-between"><p className="text-xs font-black uppercase tracking-wide text-slate-500">Resultado</p>{onRemove && <button onClick={onRemove} aria-label="Remover resultado"><X className="h-4 w-4 text-slate-400" /></button>}</div><select value={entry.section_index} onChange={(event) => { const value=Number(event.target.value);const section=value>0?sections[value-1]:undefined;onChange({section_index:value,section_type:section?.type ?? 'other'}); }} className="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm font-bold"><option value={0}>Treino completo</option>{sections.map((section,index)=><option key={index} value={index+1}>{sectionLabel(section.type)} · {section.title}</option>)}</select><input value={entry.movement} onChange={(event) => onChange({ movement:event.target.value })} placeholder="Movimento (necessário para detectar PR)" className="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm" /><select value={entry.score_type} onChange={(event) => onChange(resetScore(entry,event.target.value as AthleteResultEntry['score_type']))} className="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm font-bold">{scoreTypes.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><ScoreFields entry={entry} onChange={onChange} /></section>; }
function ScoreFields({ entry, onChange }: { entry: AthleteResultEntry; onChange: (patch: Partial<AthleteResultEntry>) => void }) { const input=(key:keyof AthleteResultEntry,label:string,step='1')=><label className="text-xs font-bold text-slate-500">{label}<input type="number" min="0" step={step} value={(entry[key] as number) || ''} onChange={(event)=>onChange({[key]:Number(event.target.value)} as Partial<AthleteResultEntry>)} className="mt-1 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-base text-slate-950" /></label>;return <div className="mt-3 grid grid-cols-2 gap-2">{entry.score_type==='time'&&<>{input('time_seconds','Tempo em segundos')}</>}{entry.score_type==='rounds_reps'&&<>{input('rounds','Rounds')}{input('repetitions','Repetições extras')}</>}{entry.score_type==='reps'&&input('repetitions','Repetições')}{entry.score_type==='load'&&input('load_kg','Carga em kg','0.5')}{entry.score_type==='distance'&&input('distance_meters','Distância em metros')}{entry.score_type==='calories'&&input('calories','Calorias')}{entry.score_type==='completed'&&<button onClick={()=>onChange({completed:!entry.completed})} className={`col-span-2 rounded-xl border py-3 font-bold ${entry.completed?'border-emerald-500 bg-emerald-50 text-emerald-700':'border-slate-200 bg-white'}`}>{entry.completed?'Concluído':'Marcar como concluído'}</button>}</div>; }

function ProfileView({ profile, installPrompt, onInstall, onLogout, onVerification }: { profile: AthleteProfile; installPrompt?: Event; onInstall:()=>void;onLogout:()=>void;onVerification:()=>Promise<void> }) { return <div className="space-y-4"><section className="rounded-[28px] bg-white p-6"><div className="grid h-16 w-16 place-items-center rounded-3xl bg-[#071426] text-xl font-black text-white">{initials(profile.name)}</div><h2 className="mt-4 text-2xl font-black">{profile.name}</h2><p className="mt-1 text-sm text-slate-500">{profile.email}</p>{profile.email_verified?<p className="mt-3 flex items-center gap-2 text-sm font-bold text-emerald-700"><ShieldCheck className="h-4 w-4" />E-mail verificado</p>:<button onClick={()=>void onVerification()} className="mt-3 text-sm font-extrabold text-orange-600">Verificar meu e-mail</button>}</section><section className="rounded-[28px] bg-white p-5"><p className="text-xs font-extrabold uppercase tracking-[.15em] text-slate-400">Meus boxes</p><div className="mt-3 space-y-3">{profile.memberships.map((item)=><div key={item.id} className="flex items-center gap-3 rounded-2xl bg-slate-50 p-4"><Dumbbell className="h-5 w-5 text-orange-600" /><div><p className="font-extrabold">{item.box_name}</p><p className="text-xs text-slate-500">Vínculo ativo desde {formatDate(item.joined_at.slice(0,10))}</p></div></div>)}</div></section>{installPrompt&&<button onClick={onInstall} className="flex w-full items-center gap-3 rounded-3xl bg-cyan-50 p-4 text-left"><Download className="h-5 w-5 text-cyan-600" /><div><p className="font-extrabold">Instalar EngageFit</p><p className="text-sm text-slate-600">Acesso rápido na tela inicial</p></div></button>}<button onClick={onLogout} className="flex w-full items-center justify-center gap-2 rounded-2xl border border-slate-200 bg-white py-3.5 text-sm font-extrabold"><LogOut className="h-4 w-4" />Sair da conta</button></div>; }

const scoreTypes: Array<[AthleteResultEntry['score_type'],string]>=[['time','Tempo'],['rounds_reps','Rounds + reps'],['reps','Repetições'],['load','Carga'],['distance','Distância'],['calories','Calorias'],['completed','Concluído']];
function newEntry(workout:AthleteWorkout):AthleteResultEntry{const formats=workout.classification?.formats??[];const score_type:AthleteResultEntry['score_type']=formats.includes('for_time')?'time':formats.includes('amrap')?'rounds_reps':formats.includes('max_effort')?'load':'completed';return{section_index:0,section_type:'other',movement:workout.classification?.movement_mentions?.[0]??'',score_type,completed:score_type==='completed'};}
function resetScore(entry:AthleteResultEntry,score_type:AthleteResultEntry['score_type']):AthleteResultEntry{return{section_index:entry.section_index,section_type:entry.section_type,movement:entry.movement,score_type,completed:score_type==='completed'};}
function Modal({children,onClose}:{children:React.ReactNode;onClose:()=>void}){return <div className="fixed inset-0 z-50 grid place-items-end bg-slate-950/60 sm:place-items-center sm:p-5" role="dialog" aria-modal="true"><section className="max-h-[94dvh] w-full max-w-xl overflow-y-auto rounded-t-[30px] bg-white p-5 shadow-2xl sm:rounded-[30px] sm:p-6">{children}</section><button className="absolute inset-0 -z-10" onClick={onClose} aria-label="Fechar" /></div>}
function Close({onClick}:{onClick:()=>void}){return <button onClick={onClick} className="grid h-10 w-10 place-items-center rounded-full bg-slate-100"><X className="h-5 w-5" /></button>}
function Nav({active,icon:Icon,label,onClick}:{active:boolean;icon:typeof Home;label:string;onClick:()=>void}){return <button onClick={onClick} className={`flex min-h-14 flex-col items-center justify-center gap-1 rounded-2xl text-[11px] font-extrabold ${active?'text-orange-600':'text-slate-400'}`}><Icon className="h-5 w-5" />{label}</button>}
function Pill({children}:{children:React.ReactNode}){return <span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-extrabold text-slate-600">{children}</span>}
function Empty(){return <section className="rounded-[28px] bg-white p-7 text-center"><Dumbbell className="mx-auto h-10 w-10 text-orange-500" /><h2 className="mt-4 text-xl font-black">O próximo treino ainda não chegou</h2><p className="mt-2 text-sm text-slate-500">Assim que o box publicar, ele aparece aqui.</p></section>}
function Brand(){return <div className="inline-flex items-center gap-2"><span className="grid h-9 w-9 place-items-center rounded-xl bg-orange-500"><Zap className="h-5 w-5 fill-current" /></span><span className="text-xl font-black">Engage<span className="text-orange-400">Fit</span></span></div>}
function featuredWorkout(items:AthleteWorkout[]){const today=localDate();return items.find(i=>i.workout_date===today)??items.find(i=>i.workout_date>today)??items[0]}
function localDate(){const now=new Date();return new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,10)}
function relativeDate(value:string){return value===localDate()?'Treino de hoje':formatDate(value)}
function formatDate(value:string){return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${value}T12:00:00`)).replace('.','')}
function sectionLabel(value:string){return({warmup:'Aquecimento',skill:'Técnica',strength:'Força',wod:'Workout of the day',accessory:'Acessório',cooldown:'Volta à calma',other:'Treino'} as Record<string,string>)[value]??'Treino'}
function formatLabel(value:string){return({amrap:'AMRAP',emom:'EMOM',for_time:'For time',tabata:'Tabata',interval:'Intervalado',max_effort:'Carga máxima'} as Record<string,string>)[value]??value}
function scaleLabel(value:string){return({rx:'RX',scaled:'Scaled',adapted:'Adaptado'} as Record<string,string>)[value]}
function resultSummary(entry?:AthleteResultEntry){if(!entry)return'Resultado salvo';switch(entry.score_type){case'time':return`${Math.floor((entry.time_seconds??0)/60)}:${String((entry.time_seconds??0)%60).padStart(2,'0')}`;case'rounds_reps':return`${entry.rounds??0} rounds + ${entry.repetitions??0}`;case'load':return`${entry.load_kg} kg`;case'reps':return`${entry.repetitions} reps`;default:return'Resultado salvo'}}
function metricLabel(value:string){return value==='load'?'Carga máxima':value==='reps'?'Máximo de repetições':'Melhor tempo'}
function recordValue(record:AthletePersonalRecord){if(record.metric==='time'){const seconds=Math.round(record.best_value);return`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`};return`${record.best_value.toLocaleString('pt-BR')} ${record.unit==='reps'?'reps':record.unit}`}
function firstName(name:string){return name.trim().split(/\s+/)[0]||'atleta'}function initials(name:string){return name.trim().split(/\s+/).slice(0,2).map(p=>p[0]?.toUpperCase()).join('')}function greeting(){const h=new Date().getHours();return h<12?'Bom dia':h<18?'Boa tarde':'Boa noite'}function tabTitle(tab:Tab){return tab==='today'?'Pronto para o próximo treino?':tab==='history'?'Sua evolução, treino a treino':tab==='records'?'Suas melhores marcas':'Seu espaço no EngageFit'}
