import type { ProductGuideSection } from '../../../components/help/ProductGuide';

export const retentionGuide: ProductGuideSection[] = [
  {
    id: 'routine',
    eyebrow: 'Visão geral',
    title: 'Uma rotina simples para começar',
    introduction: 'A Retenção organiza sinais de frequência em filas de trabalho. Ela ajuda a equipe a decidir quem observar, quem abordar e quando revisar cada acompanhamento — sem afirmar que um aluno irá cancelar.',
    image: '/help/retention/radar-visao-geral.png',
    imageAlt: 'Visão geral do Radar e ações da Retenção',
    imageCaption: 'Os três cartões resumem a fila atual; as abas abaixo organizam o estágio de cada acompanhamento.',
    steps: [
      'Abra “Precisa de ação” no início do dia e trate primeiro os casos de atenção imediata.',
      'Confira o histórico de frequência antes de abordar o aluno.',
      'Registre o contato, o resultado e uma data realista para revisão.',
      'Volte à fila “Em acompanhamento” nas datas combinadas e atualize o caso.',
    ],
    tip: 'Uma rotina curta e frequente funciona melhor: reserve de 10 a 15 minutos por dia para a fila principal e faça uma revisão semanal dos resultados.',
  },
  {
    id: 'queues',
    eyebrow: 'Radar e ações',
    title: 'Entenda as filas de trabalho',
    introduction: 'As filas representam o estágio operacional do aluno. Elas evitam contatos repetidos e deixam claro o que precisa acontecer em seguida.',
    image: '/help/retention/radar-acompanhamento.png',
    imageAlt: 'Fila Em acompanhamento com três alunos',
    imageCaption: 'Em acompanhamento reúne alunos já abordados e mostra canal, data, responsável e próxima revisão.',
    points: [
      'Precisa de ação: casos novos ou acompanhamentos cuja revisão venceu.',
      'Em acompanhamento: já existe uma ação registrada e a equipe aguarda retorno ou uma nova data de revisão.',
      'Retornos: houve nova presença após a ação registrada; ainda cabe à equipe avaliar o contexto.',
      'Pausados/encerrados: casos sem ação imediata, como pausa informada ou ausência de interesse.',
      'Todos: visão completa para consulta, busca e conferência.',
    ],
    tip: 'Não registre uma nova abordagem antes da data de revisão, salvo se houver um fato novo. Isso reduz mensagens excessivas e mantém o histórico confiável.',
  },
  {
    id: 'signals',
    eyebrow: 'Leitura dos dados',
    title: 'Leia o sinal antes de agir',
    introduction: 'O radar compara os 28 dias mais recentes com as quatro semanas anteriores. A etiqueta resume a intensidade da mudança, mas a decisão final continua sendo da equipe.',
    image: '/help/retention/radar-acompanhamento.png',
    imageAlt: 'Alunos com etiquetas de atenção e métricas de frequência',
    imageCaption: 'Cada linha combina etiqueta, explicação do sinal, recomendação e números usados na comparação.',
    points: [
      'Atenção imediata indica ausência prolongada ou queda mais relevante.',
      'Em queda indica redução perceptível na frequência recente.',
      'Observar sugere acompanhar antes de realizar uma abordagem mais ativa.',
      'Check-ins recentes correspondem aos últimos 28 dias.',
      'O histórico anterior oferece uma referência; ele não é uma previsão de cancelamento.',
    ],
    tip: 'Considere aulas especiais, feriados, viagens e mudanças de rotina antes de interpretar uma queda como desengajamento.',
  },
  {
    id: 'attendance',
    eyebrow: 'Contexto do aluno',
    title: 'Confira o histórico de frequência',
    introduction: '“Ver frequência” abre uma visão de oito semanas e um calendário mensal. Use essa tela para distinguir uma ausência pontual de uma mudança consistente no hábito.',
    image: '/help/retention/historico-frequencia.png',
    imageAlt: 'Painel lateral com histórico de frequência de uma aluna',
    imageCaption: 'As semanas mostram a distribuição das presenças; o calendário detalha dia, horário e origem do check-in.',
    steps: [
      'Observe se a queda aconteceu em uma única semana ou se continua por várias semanas.',
      'Compare os dias habituais de treino com os dias sem presença.',
      'Clique em um dia marcado no calendário para confirmar horário e plataforma.',
      'Feche o painel e escolha a abordagem adequada ao contexto observado.',
    ],
    tip: 'Quando a pessoa ainda frequenta a academia, prefira uma conversa presencial acolhedora em vez de começar por uma mensagem de cobrança.',
  },
  {
    id: 'action',
    eyebrow: 'Registro operacional',
    title: 'Registre um acompanhamento útil',
    introduction: 'O registro transforma uma conversa isolada em um acompanhamento coordenado. Preencha apenas o necessário para orientar a próxima ação da equipe.',
    image: '/help/retention/registrar-acompanhamento.png',
    imageAlt: 'Formulário para registrar acompanhamento de retenção',
    imageCaption: 'Canal, resultado, motivo percebido, responsável e revisão alimentam as filas e os indicadores.',
    steps: [
      'Informe como o contato ocorreu e qual foi o resultado observado.',
      'Selecione o motivo percebido somente quando houver contexto suficiente.',
      'Defina um responsável para evitar que duas pessoas façam a mesma abordagem.',
      'Escolha a próxima data de revisão e registre uma observação curta, se necessário.',
      'Salve o acompanhamento; o aluno será movido para a fila correspondente.',
    ],
    points: [
      'Use “Não identificado” quando o aluno não informou um motivo.',
      'Não registre diagnósticos, detalhes médicos ou informações financeiras sensíveis.',
      'Respeite a preferência de contato exibida pelo sistema.',
    ],
    tip: 'Uma boa observação responde apenas: o que foi combinado e qual é o próximo passo. Evite opiniões pessoais sobre o aluno.',
  },
  {
    id: 'first-30-days',
    eyebrow: 'Formação de hábito',
    title: 'Acompanhe os primeiros 30 dias',
    introduction: 'Essa jornada ajuda a equipe a apoiar alunos recém-iniciados na formação de uma rotina. Os contadores mostram quantas presenças ocorreram dentro das janelas de 7, 14 e 30 dias a partir da data de início.',
    image: '/help/retention/primeiros-30-dias.png',
    imageAlt: 'Jornada Primeiros 30 dias com uma aluna',
    imageCaption: 'A recomendação muda conforme a presença evolui; a data de início pode ser inferida ou confirmada pela operação.',
    points: [
      'Sem primeira presença: confirme se a data de início está correta e ofereça apoio para a primeira aula.',
      'Aguardando segunda presença: incentive a repetição enquanto a experiência inicial ainda está recente.',
      'Início recente: observe a continuidade sem criar pressão desnecessária.',
      'Uma presença no primeiro dia aparece nas três janelas, pois também está dentro de 14 e 30 dias.',
      'Confirme a data de início quando ela tiver sido inferida pelo primeiro check-in.',
    ],
    tip: 'O objetivo não é cobrar quantidade, mas identificar cedo quem precisa de orientação, acolhimento ou ajuda para encaixar o treino na rotina.',
  },
  {
    id: 'results',
    eyebrow: 'Aprendizado da operação',
    title: 'Use Resultados para melhorar a abordagem',
    introduction: 'Resultados consolida ações concluídas, retornos observados, tempo de retorno, canais e motivos registrados. Escolha um período consistente para comparar a evolução do trabalho.',
    image: '/help/retention/resultados.png',
    imageAlt: 'Painel de resultados da Retenção',
    imageCaption: 'A fila atual retrata hoje; os demais indicadores respeitam o período selecionado.',
    points: [
      'Retorno em 3, 7 ou 14 dias significa que houve presença após uma ação concluída.',
      'A mediana considera somente casos com retorno observado em até 14 dias.',
      'Um traço no tempo de retorno significa que ainda não há casos válidos para calcular a mediana.',
      'Motivos e canais dependem da qualidade dos registros feitos pela equipe.',
      'A associação temporal não prova que o contato foi a causa do retorno.',
    ],
    tip: 'Compare períodos de pelo menos quatro semanas. Amostras muito pequenas mudam rapidamente e não devem orientar decisões definitivas.',
  },
  {
    id: 'best-practices',
    eyebrow: 'Cultura de relacionamento',
    title: 'Boas práticas para toda a equipe',
    introduction: 'A ferramenta funciona melhor quando a academia estabelece uma forma respeitosa e consistente de acompanhar seus alunos.',
    points: [
      'Aborde com curiosidade e acolhimento, nunca com culpa ou pressão.',
      'Priorize conversas presenciais quando o aluno ainda está frequentando.',
      'Personalize a conversa com base no contexto, sem mencionar “risco de cancelamento”.',
      'Registre o resultado logo após o contato e cumpra a data de revisão combinada.',
      'Mantenha anotações objetivas e evite dados pessoais sensíveis.',
      'Use os resultados para aprender sobre o processo, não para avaliar individualmente o desempenho de um coach.',
    ],
    steps: [
      'Diariamente: trate a fila “Precisa de ação” e as revisões vencidas.',
      'Semanalmente: revise acompanhamentos sem avanço e distribua responsáveis.',
      'Mensalmente: analise resultados, canais e motivos percebidos com a equipe.',
    ],
    tip: 'Retenção é consequência de relacionamento, experiência e consistência. O radar organiza o trabalho; a qualidade da conversa continua sendo humana.',
  },
];
